### PR TITLE
Call g2c library for pngpack/pngunpack and jpcpack/jpcunpack

### LINKED ISSUE #169: C files enc_png, enc_jpeg2000, dec_png, dec_jpeg2000 are already in g2c and are copied here
We have apparently copied some C files from the g2c project into the g2 project. Of course this is not the correct way to handle the need for this functionality.

Duplicated code leads to preventable bugs, increased maintenance costs, developer confusion, and higher project risks. We will not engage in such hacks with NCEPLIBS.

So instead, we need to have NCEPLIBS-g2 depend on g2c, and call the already existing functions in g2c. That's why we put them in a library in the first place, right?

### LINKED ISSUE #236: on new install, build breaks for newer jasper library
Recently my hard drive failed and I had to replace it.

This means I am building everything from scratch which is interesting ;-)

I installed jpeg with apt-get, and cmake claims to find what it needs for jpeg:

```
ed@mikado:~/NCEPLIBS-g2/b$ cmake .. -DCMAKE_PREFIX_PATH="/usr/local/jasper-3.0.3;/usr/local/NCELIBS-bacio"
-- The C compiler identification is GNU 9.4.0
-- The Fortran compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working Fortran compiler: /usr/bin/gfortran
-- Check for working Fortran compiler: /usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 -- yes
-- Setting build type to 'Release' as none was specified.
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so (found version "80") 
-- Found Jasper: /usr/local/jasper-3.0.3/lib/libjasper.so (found suitable version "3.0.3", minimum required is "2.0.25") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.37") 
-- Found bacio: /usr/local/NCELIBS-bacio/lib/libbacio.a (found version "2.5.0")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ed/NCEPLIBS-g2/b
```

Yet when I try to build, it fails on the JPEG library:

```
Scanning dependencies of target g2_4_c
[ 73%] Building C object src/CMakeFiles/g2_4_c.dir/dec_jpeg2000.c.o
[ 73%] Building C object src/CMakeFiles/g2_4_c.dir/dec_png.c.o
[ 74%] Building C object src/CMakeFiles/g2_4_c.dir/enc_jpeg2000.c.o
[ 74%] Building C object src/CMakeFiles/g2_4_c.dir/enc_png.c.o
[ 75%] Building C object src/CMakeFiles/g2_4_c.dir/mova2i.c.o
[ 75%] Built target g2_4_c
Scanning dependencies of target g2_4
[ 75%] Linking Fortran static library libg2_4.a
[ 75%] Built target g2_4
Scanning dependencies of target g2_test_lib
[ 75%] Building Fortran object tests/CMakeFiles/g2_test_lib.dir/creategrib.f90.o
[ 76%] Linking Fortran static library libg2_test_lib.a
[ 76%] Built target g2_test_lib
Scanning dependencies of target test_gribcreate
[ 77%] Building Fortran object tests/CMakeFiles/test_gribcreate.dir/test_gribcreate.f90.o
[ 77%] Linking Fortran executable test_gribcreate
/usr/bin/ld: ../src/libg2_4.a(enc_jpeg2000.c.o): in function `enc_jpeg2000_':
/home/ed/NCEPLIBS-g2/src/enc_jpeg2000.c:145: undefined reference to `jpc_encode'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/test_gribcreate.dir/build.make:93: tests/test_gribcreate] Error 1
make[1]: *** [CMakeFiles/Makefile2:1137: tests/CMakeFiles/test_gribcreate.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

```

Seems like this is related to changes in the jasper library. See https://github.com/NOAA-EMC/NCEPLIBS-wgrib2/issues/53.

### LINKED ISSUE #290: Add call to g2c_set_log_level() so fortran programs can turn on logging
Add call to g2c_set_log_level() so fortran programs can turn on logging

### PR DESCRIPTION
**Pull request by edwardhartnett**
Some C codes had been copied from the g2c library into the g2 library, and compiled as part of g2 as well as g2c. Of course the jasper library changed breaking this code. 

Instead of fixing it in both g2c and g2, I have made g2 call the g2c code and fixed it there. Now the code only lives in one place.

The g2 library also reimplemented the code in the g2c functions pngpack/pngunpack and jpcpack/jpcunpack. Now the g2 library calls the g2c library for these, and the extra fortran code can be removed.

This is the first in a series of PRs which will eliminate fortran code which implements functions already in the C library.

Also added logging to the Fortran library.

Fixes #290 
Fixes #236 
Fixes #169
Part of #23

### CODE REVIEW

**Comment by edwardhartnett** [comment]
This PR will not pass until the next version of g2c is released, and the CI in this repo changed to use the new version.

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA this is ready for review...

**Review by Hang-Lei-NOAA — APPROVED** [review]
As a result, the g2 lib has the dependency of g2c lib. g2c come to the top of this series.

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA as you point out this PR introduces a dependency on g2c. However, I think I can remove the dependency on Jasper now. I will give that a try.

This is just the beginning - there are many duplicated codes between C and Fortran. We will be keeping the C and not the Fortran in all cases.

**Pull request merged**
