### PR TITLE
Improving testing for gettemplates.f

### LINKED ISSUE #375: Test for gettemplates.f
This code is completely untested.

### PR DESCRIPTION
**Pull request by kingofnart**
Removing extra GRIB message arrays, adding non-error function call.

Fixes #375

### CODE REVIEW

**Review by edwardhartnett — APPROVED** [review]

**Comment by edwardhartnett** [comment]
OK, you are running afoul of some of the new memory tests:

	 48 - test_gettemplates_4 (Failed)
	 79 - test_gettemplates_d (Failed)
-- Processing memory checking output:
48/80 MemCheck: #48: test_gettemplates_4 ..............   Defects: 7
79/80 MemCheck: #79: test_gettemplates_d ..............   Defects: 7
MemCheck log files can be found here: (<#> corresponds to test number)
/home/runner/work/NCEPLIBS-g2/NCEPLIBS-g2/g2/build/Testing/Temporary/MemoryChecker.<#>.log
Memory checking results:
Uninitialized Memory Conditional - 12
Uninitialized Memory Read - 2

I just added these tests and got them working elsewhere in the build. There were actually lots of memory problems!

I'll discuss memory checking in the meeting tomorrow. In the meantime, build on your own machine, and then run:

ctest -T memcheck

and it will run the memory checking. (You may have to do sudo apt-get install valgrind).

THen the memory checking output will be on your system in the files indicated in the error message and you can see exactly where your leaks are.

**Comment by kingofnart** [comment]
I'm having some issues with running the ctest -T memcheck command. First the output shows that 0/80 tests passed 

`0% tests passed, 80 tests failed out of 80`

but then I look at the file LastTest.log and I see
```
48/80 Testing: test_gettemplates_4
48/80 Test: test_gettemplates_4
Command: "/home/andrew/Documents/VSCode/NCEPLIBS-g2/build/tests/test_gettemplates_4"
Directory: /home/andrew/Documents/VSCode/NCEPLIBS-g2/build/tests
"test_gettemplates_4" start time: Jul 20 10:48 MDT
Output:
----------------------------------------------------------
 Calling gribinfo ...
 Max igdstmpl:           67 , size:           67
 Max ipdstmpl:           62 , size:           62
 Max drs:           36
 Max coordlist(7):          225 , size:          225
 Testing gettemplates ...
 gettemplates: Request for field number must be positive.
 gettemplates:  Beginning characters GRIB not found.
 gettemplates: GRIB message contained            0  different fields.
 gettemplates: The request was for the            9  field.
 SUCCESS!
<end of output>
Test time =   0.03 sec
----------------------------------------------------------
Test Passed.
"test_gettemplates_4" end time: Jul 20 10:48 MDT
"test_gettemplates_4" time elapsed: 00:00:00
```
and
```
79/80 Testing: test_gettemplates_d
79/80 Test: test_gettemplates_d
Command: "/home/andrew/Documents/VSCode/NCEPLIBS-g2/build/tests/test_gettemplates_d"
Directory: /home/andrew/Documents/VSCode/NCEPLIBS-g2/build/tests
"test_gettemplates_d" start time: Jul 20 10:48 MDT
Output:
----------------------------------------------------------
 Calling gribinfo ...
 Max igdstmpl:           67 , size:           67
 Max ipdstmpl:           62 , size:           62
 Max drs:           36
 Max coordlist(7):          225 , size:          225
 Testing gettemplates ...
 gettemplates: Request for field number must be positive.
 gettemplates:  Beginning characters GRIB not found.
 gettemplates: GRIB message contained            0  different fields.
 gettemplates: The request was for the            9  field.
 SUCCESS!
<end of output>
Test time =   0.02 sec
----------------------------------------------------------
Test Passed.
"test_gettemplates_d" end time: Jul 20 10:48 MDT
"test_gettemplates_d" time elapsed: 00:00:00
```
All the other memory tests are passing as well in the .log file.
I also have been getting the error ```/snap/core20/current/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libproxy.so.1)
Failed to load module: /home/andrew/snap/code/common/.cache/gio-modules/libgiolibproxy.so``` but when I run the command `strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX` I get
```
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_3.4.29
GLIBCXX_3.4.30
GLIBCXX_3.4.31
GLIBCXX_3.4.32
GLIBCXX_TUNABLES
GLIBCXX_DEBUG_MESSAGE_LENGTH
```
Not sure if this is relevant but thought I should mention it.

**Comment by kingofnart** [comment]
Here is the output from the valgrind command:
```
==230324== Memcheck, a memory error detector
==230324== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==230324== Using Valgrind-3.18.1-42b08ed5bd-20211015 and LibVEX; rerun with -h for copyright info
==230324== Command: ./test_gettemplates_4
==230324== 
--230324-- Valgrind options:
--230324--    --leak-check=full
--230324--    --show-leak-kinds=all
--230324--    --track-origins=yes
--230324--    --verbose
--230324-- Contents of /proc/version:
--230324--   Linux version 5.19.0-45-generic (buildd@lcy02-amd64-117) (x86_64-linux-gnu-gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #46~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 7 15:06:04 UTC 20
--230324-- 
--230324-- Arch and hwcaps: AMD64, LittleEndian, amd64-cx16-lzcnt-rdtscp-sse3-ssse3-avx-avx2-bmi-f16c-rdrand-rdseed
--230324-- Page sizes: currently 4096, max supported 4096
--230324-- Valgrind library directory: /usr/libexec/valgrind
--230324-- Reading syms from /home/andrew/Documents/VSCode/NCEPLIBS-g2/build/tests/test_gettemplates_4
--230324-- Reading syms from /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
--230324--   Considering /usr/lib/debug/.build-id/61/ef896a699bb1c2e4e231642b2e1688b2f1a61e.debug ..
--230324--   .. build-id is valid
--230324-- Reading syms from /usr/libexec/valgrind/memcheck-amd64-linux
--230324--    object doesn't have a symbol table
--230324--    object doesn't have a dynamic symbol table
--230324-- Scheduler: using generic scheduler lock implementation.
--230324-- Reading suppressions file: /usr/libexec/valgrind/default.supp
==230324== embedded gdbserver: reading from /tmp/vgdb-pipe-from-vgdb-to-230324-by-andrew-on-???
==230324== embedded gdbserver: writing to   /tmp/vgdb-pipe-to-vgdb-from-230324-by-andrew-on-???
==230324== embedded gdbserver: shared mem   /tmp/vgdb-pipe-shared-mem-vgdb-230324-by-andrew-on-???
==230324== 
==230324== TO CONTROL THIS PROCESS USING vgdb (which you probably
==230324== don't want to do, unless you know exactly what you're doing,
==230324== or are doing some strange experiment):
==230324==   /usr/bin/vgdb --pid=230324 ...command...
==230324== 
==230324== TO DEBUG THIS PROCESS USING GDB: start GDB like this
==230324==   /path/to/gdb ./test_gettemplates_4
==230324== and then give GDB the following command
==230324==   target remote | /usr/bin/vgdb --pid=230324
==230324== --pid is optional if only one valgrind process is running
==230324== 
--230324-- REDIR: 0x402aa60 (ld-linux-x86-64.so.2:strlen) redirected to 0x580bcec2 (???)
--230324-- REDIR: 0x402a830 (ld-linux-x86-64.so.2:index) redirected to 0x580bcedc (???)
--230324-- Reading syms from /usr/libexec/valgrind/vgpreload_core-amd64-linux.so
--230324--    object doesn't have a symbol table
--230324-- Reading syms from /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so
--230324--    object doesn't have a symbol table
==230324== WARNING: new redirection conflicts with existing -- ignoring it
--230324--     old: 0x0402aa60 (strlen              ) R-> (0000.0) 0x580bcec2 ???
--230324--     new: 0x0402aa60 (strlen              ) R-> (2007.0) 0x0484ee30 strlen
--230324-- REDIR: 0x4027240 (ld-linux-x86-64.so.2:strcmp) redirected to 0x484fcd0 (strcmp)
--230324-- REDIR: 0x402afc0 (ld-linux-x86-64.so.2:mempcpy) redirected to 0x4853840 (mempcpy)
--230324-- Reading syms from /usr/lib/x86_64-linux-gnu/libasan.so.6.0.0
--230324-- Reading syms from /usr/lib/x86_64-linux-gnu/libpng16.so.16.37.0
--230324--    object doesn't have a symbol table
--230324-- Reading syms from /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
--230324--    object doesn't have a symbol table
--230324-- Reading syms from /home/andrew/local/jasper-4.0.0/lib/libjasper.so.7.0.0
--230324-- Reading syms from /usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2
--230324--    object doesn't have a symbol table
--230324-- Reading syms from /usr/lib/x86_64-linux-gnu/libgfortran.so.5.0.0
--230324--    object doesn't have a symbol table
--230324-- Reading syms from /usr/lib/x86_64-linux-gnu/libm.so.6
--230324--   Considering /usr/lib/debug/.build-id/27/e82301dba6c3f644404d504e1bb1c97894b433.debug ..
--230324--   .. build-id is valid
--230324-- Reading syms from /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
--230324--    object doesn't have a symbol table
--230324-- Reading syms from /usr/lib/x86_64-linux-gnu/libquadmath.so.0.0.0
--230324--    object doesn't have a symbol table
--230324-- Reading syms from /usr/lib/x86_64-linux-gnu/libc.so.6
--230324--   Considering /usr/lib/debug/.build-id/69/389d485a9793dbe873f0ea2c93e02efaa9aa3d.debug ..
--230324--   .. build-id is valid
==230324== WARNING: new redirection conflicts with existing -- ignoring it
--230324--     old: 0x05880ce0 (memalign            ) R-> (1011.0) 0x0484e080 memalign
--230324--     new: 0x05880ce0 (memalign            ) R-> (1017.0) 0x0484e050 aligned_alloc
==230324== WARNING: new redirection conflicts with existing -- ignoring it
--230324--     old: 0x05880ce0 (memalign            ) R-> (1011.0) 0x0484e080 memalign
--230324--     new: 0x05880ce0 (memalign            ) R-> (1017.0) 0x0484e020 aligned_alloc
==230324== WARNING: new redirection conflicts with existing -- ignoring it
--230324--     old: 0x05880ce0 (memalign            ) R-> (1011.0) 0x0484e080 memalign
--230324--     new: 0x05880ce0 (memalign            ) R-> (1017.0) 0x0484e050 aligned_alloc
==230324== WARNING: new redirection conflicts with existing -- ignoring it
--230324--     old: 0x05880ce0 (memalign            ) R-> (1011.0) 0x0484e080 memalign
--230324--     new: 0x05880ce0 (memalign            ) R-> (1017.0) 0x0484e020 aligned_alloc
--230324-- REDIR: 0x58837a0 (libc.so.6:strnlen) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x5883a60 (libc.so.6:strpbrk) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x5883360 (libc.so.6:strcmp) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x58a1d50 (libc.so.6:wcsnlen) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x5884750 (libc.so.6:memset) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x58a05c0 (libc.so.6:wcslen) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x5884c90 (libc.so.6:memcpy@@GLIBC_2.14) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x58a03f0 (libc.so.6:wcschr) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x58832e0 (libc.so.6:index) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x58839e0 (libc.so.6:rindex) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x5884620 (libc.so.6:memmove) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
==230324== Preferring higher priority redirection:
--230324--     old: 0x0597b940 (__memcpy_avx_unalign) R-> (2018.0) 0x04850f90 __memcpy_avx_unaligned_erms
--230324--     new: 0x0597b940 (__memcpy_avx_unalign) R-> (2018.1) 0x04852880 memmove
--230324-- REDIR: 0x58a0470 (libc.so.6:wcscmp) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x5884a60 (libc.so.6:stpncpy) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x58a0a30 (libc.so.6:wmemchr) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x58838b0 (libc.so.6:strncmp) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x5884af0 (libc.so.6:strcasecmp) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x58834a0 (libc.so.6:strcspn) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x58a04f0 (libc.so.6:wcscpy) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x5883250 (libc.so.6:strcat) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x5884be0 (libc.so.6:strncasecmp_l) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x5884500 (libc.so.6:bcmp) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x588c5f0 (libc.so.6:memrchr) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x5886090 (libc.so.6:strchrnul) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x5883410 (libc.so.6:strcpy) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x5884b90 (libc.so.6:strcasecmp_l) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x5883720 (libc.so.6:strlen) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x5883950 (libc.so.6:strncpy) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x58849d0 (libc.so.6:stpcpy) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x5884470 (libc.so.6:memchr) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x5883b80 (libc.so.6:strspn) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x5884850 (libc.so.6:mempcpy) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x5884b40 (libc.so.6:strncasecmp) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x5886000 (libc.so.6:rawmemchr) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
--230324-- REDIR: 0x590f430 (libc.so.6:__memcpy_chk) redirected to 0x483f220 (_vgnU_ifunc_wrapper)
==230324==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
--230324-- REDIR: 0x491e430 (libasan.so.6:free) redirected to 0x484b210 (free)
==230324== 
==230324== Process terminating with default action of signal 11 (SIGSEGV)
==230324==  General Protection Fault
==230324==    at 0x5874F42: __pthread_once_slow (pthread_once.c:114)
==230324==    by 0x5943A52: __rpc_thread_variables (rpc_thread.c:59)
==230324==    by 0x5996D8C: free_mem (in /usr/lib/x86_64-linux-gnu/libc.so.6)
==230324==    by 0x59968C1: __libc_freeres (in /usr/lib/x86_64-linux-gnu/libc.so.6)
==230324==    by 0x483F1B2: _vgnU_freeres (in /usr/libexec/valgrind/vgpreload_core-amd64-linux.so)
==230324==    by 0x4A523DF: ???
==230324==    by 0x49482B6: __sanitizer::Die() (sanitizer_termination.cpp:59)
==230324==    by 0x491E398: __asan::AsanCheckDynamicRTPrereqs() (asan_linux.cpp:181)
==230324==    by 0x492A544: __asan::AsanInitInternal() [clone .part.0] (asan_rtl.cpp:420)
==230324==    by 0x40065BD: _dl_init (dl-init.c:102)
==230324==    by 0x40202E9: ??? (in /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2)
==230324== 
==230324== HEAP SUMMARY:
==230324==     in use at exit: 0 bytes in 0 blocks
==230324==   total heap usage: 0 allocs, 0 frees, 0 bytes allocated
==230324== 
==230324== All heap blocks were freed -- no leaks are possible
==230324== 
==230324== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
It looks like it gets a seg fault, but the program runs fine on its own.

**Comment by kingofnart** [comment]
I think I found out why valgrind was failing with a seg fault. It was because I was enabling ASan in my build command with "-fsanitize=address" and it no longer faulted when I removed them, so I was able to find out what part of the code was giving a memory error.

**Comment by kingofnart** [comment]
I was able to get to 100% code coverage if `numlocal` is changed to `numfld` on line 203 in gettemplates.f i.e.
Old: `print *,'gettemplates: GRIB message contained ',numlocal,` ...
New: `print *,'gettemplates: GRIB message contained ',numfld,` ...
Which makes more sense to me because `numlocal` isn't referenced anywhere else in the program whereas `numfld` is at least initialized in the code and compared with `ifldnum` which is also mentioned in the error message.

**Comment by edwardhartnett** [comment]
Yes, asan does not play well with valgrind, or debuggers either. ;-)

**Review by edwardhartnett — APPROVED** [review]
Thanks, looks good!

**Pull request merged**
