### PR TITLE
Adding a test creating a GRIB2 message

### LINKED ISSUE #140: Add address santize to GNU CI builds
We  get a lot of benefit from simply adding:

-fsantize=address

to the FFLAGS. Memory use is checked and great diagnostic message are printed on errors, which pinpoint the problem. Better than valgrind! ;-)

### PR DESCRIPTION
**Pull request by edwardhartnett**
Add a test that creates and then decodes a message.

This test can be further developed in a future PR.

Part of #132
Part of #26
Fixes #140

### CODE REVIEW

**Comment by BoiVuong-NOAA** [comment]
The code table PDT 4.0 is at this link: https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp4-0.shtml
For more information, NCEP WMO GRIB2 documentation is at this link: https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/

**Comment by edwardhartnett** [comment]
OK, so what is a valid Product Definition Template Number? That is not clear to me...

**Comment by BoiVuong-NOAA** [comment]
The Product Definition Template Number is 0, 8 or 11,.. of PDT in GRIB2 
table.  In GFS, we have Product Definition Template Number 0 or 8.

**Comment by edwardhartnett** [comment]
OK, where is the Product Definition Template Number defined as 0, 8, or 11? Is there a table that contains that info?

Why not -1, 7, or 13?

Where are these numbers listed?

**Comment by edwardhartnett** [comment]
OK, I changed the Product Definition Template Number to 8, the test still crashes. Let's move on to the next parameter:

```
  ! Contains the data values for the specified Product Definition
  ! Template (N=ipdsnum). Each element of this integer array contains
  ! an entry (in the order specified) of Product Defintion Template
  ! 4.N.

```

What does this mean? What does "4.N" mean in the above?

**Comment by BrianCurtis-NOAA** [comment]
When I run this test it gives me 
```
Output:
----------------------------------------------------------
 Testing g2 library encoding.
 gribend: Section 8 can only be added after Section 7.
 gribend: Section            3  was the last found in given GRIB message.
STOP 4
```
Seems like it wants a few more sections. (I couldn't ascertain whether all sections were mandatory)
Try adding 4 and 7 to start and see if it goes through.

**Comment by edwardhartnett** [comment]
OK, I plan on further extending this test, but it has reached a good point to merge to develop and start running in CI.

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA and @BrianCurtis-NOAA can you please review? I would like to get this test into play...

**Review by BrianCurtis-NOAA — APPROVED** [review]
I think we need to define some outlines for doxygen formatting that will apply to all NCEPLIBS (at least to start) codes. I note for example that you add "Initial" to first author entries in author log, and we've just added tables to the program log format. I think they're all good ideas. Maybe they should be docuented somewhere and applied everywhere. That way new code doxygen can follow it too.

**Pull request merged**
