### PR TITLE
Add AEC compression

### LINKED ISSUE #458: new compression AEC
Hi Edward and Eric,

I got a bounce back from Boi's email address. 

Do either of you know who is the current maintainer of the NCEPLIBS-g2c library?

Thanks
Arthur

On 6/28/2023 10:18 AM, Arthur Taylor wrote:
Hi Boi,

Are you still in charge of the NCEPLIBS-g2c library?

It looks like ECMWF is using a new compression scheme.  Do you know if the g2c library supports it?  If not, do you know if there are plans to support it?

Thanks,
Arthur

-------- Forwarded Message --------
Subject:	ECMWF Changes
Date:	Wed, 28 Jun 2023 14:39:10 +0100
From:	Karl Devine <karl@netweather.tv>
To:	Arthur.Taylor@noaa.gov, Michael.Allard@noaa.gov

Hi,
Sorry to be a pain but ECMWF have made some big changes so degrib no longer works with those files:

$filename="$dbdate$dbtime"."0000-$ext"."h-oper-fc.grib2";
$ftpdir="https://data.ecmwf.int/forecasts/$dbdate/$dbtime"."z"."/0p4-beta/oper";

The changes are detailed at: 
https://confluence.ecmwf.int/display/FCST/Implementation+of+IFS+Cycle+48r1

I think it's mostly compression related but i get the following error:

getdrstemplate: DRS Template 5.42 not defined.
ERROR: In call to Grib2Convert.
ERROR: In call to ReadGrib2Record.
ERROR: Unpack library error code (500 2)

I do hope it's possible to apply these changes to degrib and wgrib2 .

Many thanks

Karl De Vine

### LINKED ISSUE #705: require g2c during build, remove duplicate C code for compression from g2, use g2c directly
Currently we have some C code copied from g2c in the g2 project: g2cjpeg2000.c and g2cpng.c.

These are both in the g2c library. We need to make the g2c library mandatory in the build, and use these functions from g2c, instead of having duplicate copies of the code.

We then need to add AEC to the g2 library, using it's implementation in the g2c library.

Also, whenever we call C, we need to make sure we are using the ISO standard C/Fortran API, not relying on the underscore trick, which is not standard.

### PR DESCRIPTION
**Pull request by AlysonStahl-NOAA**
Fixes #705 
Fixes #458

### CODE REVIEW

**Comment by AlysonStahl-NOAA** [comment]
I believe this will work after NOAA-EMC/NCEPLIBS-g2c#512 is merged

**Comment by AlysonStahl-NOAA** [comment]
I could only get the spack workflow to work if I turn aec default=False. Otherwise, I get the error below. 

```
==> Error: ProcessError: Command exited with status 2:
    'make' '-j2' 'test'

3 warnings found in build log:
     25     -- Copying test file ref_gdaswave.t00z.wcoast.0p16.f000.grb2index2
     26     -- Copying test file g1.grib2
     27     -- Copying test file gdaswave.t00z.wcoast.0p16.f000.grib2
     28     -- Copying test file ref_test_jpcpack_4_output.txt
     29     -- Configuring done (0.4s)
     30     -- Generating done (0.1s)
  >> 31     CMake Warning:
     32       Manually-specified variables were not used by the project:
     33     
     34         CMAKE_POLICY_DEFAULT_CMP0090
     35         G2C_COMPARE
     36     
     37     

     ...

     120    
     121      678 |      call simunpack(cgrib(ipos), lensec-5, idrstmpl, ndpts,
             fld)
     122          |                                                            
            2
     123    ......
     124      686 |      call simunpack(cgrib(ipos), lensec-5, idrstmpl, ndpts-
            1, fld(2))
     125          |                                                            
              1
  >> 126    Warning: Element of assumed-shape or pointer array as actual argume
            nt at (1) cannot correspond to actual argument at (2)
     127    [ 19%] Building Fortran object src/CMakeFiles/g2_4_f.dir/g2create.F
            90.o
     128    cd /tmp/runner/spack-stage/spack-stage-g2-develop-w4caohczsnsc3axnf
            hyjqont476hjnpg/spack-build-w4caohc/src && /home/runner/work/NCEPLI
            BS-g2/NCEPLIBS-g2/spack-root/lib/spack/env/gcc/gfortran -DKIND=4 -D
            USE_AEC  -g -funroll-loops  -fallow-argument-mismatch -O3 -Jinclude
            _4 -c /home/runner/work/NCEPLIBS-g2/NCEPLIBS-g2/spack-devpkg-g2/src
            /g2create.F90 -o CMakeFiles/g2_4_f.dir/g2create.F90.o
     129    /home/runner/work/NCEPLIBS-g2/NCEPLIBS-g2/spack-devpkg-g2/src/g2cre
            ate.F90:446:18:
     130    
     131      442 |      call simpack(pfld, ndpts, idrstmpl, cpack, lcpack)
     132          |                  2
     133    ......
     134      446 |      call simpack(pfld(2), ndpts-1, idrstmpl, cpack, lcpack
            )
     135          |                  1
  >> 136    Warning: Element of assumed-shape or pointer array as actual argume
            nt at (1) cannot correspond to actual argument at (2)
     137    [ 20%] Building Fortran object src/CMakeFiles/g2_4_f.dir/g2sim.F90.
            o
     138    cd /tmp/runner/spack-stage/spack-stage-g2-develop-w4caohczsnsc3axnf
            hyjqont476hjnpg/spack-build-w4caohc/src && /home/runner/work/NCEPLI
            BS-g2/NCEPLIBS-g2/spack-root/lib/spack/env/gcc/gfortran -DKIND=4 -D
            USE_AEC  -g -funroll-loops  -fallow-argument-mismatch -O3 -Jinclude
            _4 -c /home/runner/work/NCEPLIBS-g2/NCEPLIBS-g2/spack-devpkg-g2/src
            /g2sim.F90 -o CMakeFiles/g2_4_f.dir/g2sim.F90.o
     139    /usr/local/bin/cmake -E touch src/CMakeFiles/g2_4_f.dir/drstemplate
            s.F90.o.provides.build
     140    /usr/local/bin/cmake -E touch src/CMakeFiles/g2_4_f.dir/g2grids.F90
            .o.provides.build
     141    /usr/local/bin/cmake -E touch src/CMakeFiles/g2_4_f.dir/g2logging.F
            90.o.provides.build
     142    /usr/local/bin/cmake -E touch src/CMakeFiles/g2_4_f.dir/gribmod.F90
            .o.provides.build

See build log for details:
  /tmp/runner/spack-stage/spack-stage-g2-develop-w4caohczsnsc3axnfhyjqont476hjnpg/spack-build-out.txt

See test log for details:
  /tmp/runner/spack-stage/spack-stage-g2-develop-w4caohczsnsc3axnfhyjqont476hjnpg/install-time-test-log.txt

Error: Process completed with exit code 1.
```

**Comment by edwardhartnett** [comment]
THese are two persistent warnings in g2 which I have not fixed. If you fix them, these errors will go away.

**Comment by AlexanderRichert-NOAA** [comment]
The warnings are not the cause of the failure, it seems to be an issue with the unit tests. I'm looking into this now.

**Comment by AlexanderRichert-NOAA** [comment]
I tweaked the Spack test action to provide the CTest output on failure. If you look at the LastTest.log in https://github.com/NOAA-EMC/NCEPLIBS-g2/actions/runs/11019572999/artifacts/1973272854 you'll see that it's failing on test_aecpack_d on STOP 6:
```
38/40 Testing: test_aecpack_d
38/40 Test: test_aecpack_d
Command: "/tmp/runner/spack-stage/spack-stage-g2-develop-7ssidmxvtjipiymvihcdx4rzwnf66acd/spack-build-7ssidmx/tests/test_aecpack_d"
Directory: /tmp/runner/spack-stage/spack-stage-g2-develop-7ssidmxvtjipiymvihcdx4rzwnf66acd/spack-build-7ssidmx/tests
"test_aecpack_d" start time: Sep 24 18:40 UTC
Output:
----------------------------------------------------------
 Testing aecpack()/aecunpack()...
 Testing aecpack/aecunpack with no data...
 lcpack:            0
 ok!
 Testing aecpack/aecunpack with constant data...
 ok!
 Testing aecpack/aecunpack with data...
   2.0000000000000000        1.0000000000000000      do not match
STOP 6
<end of output>
Test time =   0.00 sec
```

**Comment by AlysonStahl-NOAA** [comment]
> I tweaked the Spack test action to provide the CTest output on failure. If you look at the LastTest.log in https://github.com/NOAA-EMC/NCEPLIBS-g2/actions/runs/11019572999/artifacts/1973272854 you'll see that it's failing on test_aecpack_d on STOP 6:

This test was failing due to the issue I addressed in NOAA-EMC/NCEPLIBS-g2c#512. I forced it to use the develop branch of g2c when aec is on which fixed it.

**Review by edwardhartnett — APPROVED** [review]

**Pull request merged**
