### PR TITLE
adding utils to code coverage

### LINKED ISSUE #754: add utils to the code coverage analysis in the developer workflow
Right now we're only showing src in the code coverage analysis. We need to include utils.

### PR DESCRIPTION
**Pull request by AlysonStahl-NOAA**
Fixes #754

### CODE REVIEW

**Comment by edwardhartnett** [comment]
How is this coming?

**Comment by AlysonStahl-NOAA** [comment]
There's still the matter of the memory problems with utils test, so I've been working to see if I can fix them so we can finally include them in the test coverage. It's been a little tricky.

Is there a way to still include the tests in the test coverage without including them in the memory checks? If so, do you think it would be better to do that, then fix the memory issues in another PR?

**Comment by edwardhartnett** [comment]
Yes, separate the code coverage from the memory issue.

Turn off memory checking for utils, but leave on code coverage.

Let me know if you need help. On another repo I found it useful to have separate runs for asan, code coverage, and warning check. So you can do what you need to get things to work.

**Review by edwardhartnett — APPROVED** [review]

**Comment by edwardhartnett** [comment]
Is this ready to merge?

**Comment by AlysonStahl-NOAA** [comment]
Yep

**Pull request merged**
