### PR TITLE
trying to add w3emc dependency

### LINKED ISSUE #229: Add w3emc dependency in support of gdt2gds.F90 which is used by grib_util
While writing a unit test for the gdt2gds.F90 code, I noticed that it uses w3emc calls for https://github.com/NOAA-EMC/NCEPLIBS-w3emc/blob/develop/src/w3fi71.f and https://github.com/NOAA-EMC/NCEPLIBS-w3emc/blob/develop/src/r63w72.f at the following two locations:

https://github.com/NOAA-EMC/NCEPLIBS-g2/blob/9a52944bb58f77cd6bb88252f00e41f8c98af552/src/gdt2gds.F90#L344

and

https://github.com/NOAA-EMC/NCEPLIBS-g2/blob/9a52944bb58f77cd6bb88252f00e41f8c98af552/src/gdt2gds.F90#L364

There is currently no w3emc dependency inside g2. Also I would assume nobody is using that code considering the missing dependency has been around for a long time.

We should remove it.

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #229 

Trying to add w3emc dependency. Not working though...

### CODE REVIEW

**Comment by edwardhartnett** [comment]
@kgerheiser can you give me some CMake help with this one?

The test compile is failing like this:

```
[ 77%] Linking Fortran executable test_g2 /usr/bin/ld: cannot find
-lw3emc:w3emc_d: No such file or directory collect2: error: ld
returned 1 exit status make[2]: ***
[tests/CMakeFiles/test_g2.dir/build.make:105: tests/test_g2] Error 1
make[1]: *** [CMakeFiles/Makefile2:1127:
tests/CMakeFiles/test_g2.dir/all] Error 2 make: *** [Makefile:146:
all] Error 2
```

Yet in my src/CMakeLists.txt file I have this, which I thought would work:

`  target_link_libraries(${lib_name} PUBLIC bacio::bacio ${PNG_LIBRARIES} ${JASPER_LIBRARIES} w3emc:w3emc_${kind})
`
What am I doing wrong?

**Comment by kgerheiser** [comment]
Missing a colon. The target name should be `w3emc::w3emc_d` not `w3emc:we3emc_d`. CMake is interpreting your string as a literal library name and attempting to do `-lw3emc:w3emc_d`.

**Comment by edwardhartnett** [comment]
Duh...
image

**Comment by edwardhartnett** [comment]
Looks like all the Macs at GitHub need a reboot! I will rerun the CI...

**Comment by edwardhartnett** [comment]
@kgerheiser can you review please?

**Review by kgerheiser — APPROVED** [review]

**Pull request merged**
