### PR TITLE
added bacio back

### LINKED ISSUE #154: Function baread() from bacio is called from src/getgb2r.f, but bacio is neither found nor linked...
In subroutine GETGB2R() there are calls to the bacio library:

For example note the calls to BAREAD() around line 206:

```
C  READ AND UNPACK BIT_MAP, IF PRESENT
      IF ( gfld%ibmap.eq.0.OR.gfld%ibmap.eq.254 ) THEN
         ISKIP=LSKIP+SKIP6
         CALL BAREAD(LUGB,ISKIP,4,LREAD,CSIZE)    ! GET LENGTH OF SECTION
         CALL G2_GBYTEC(CSIZE,ILEN,0,32)
         ALLOCATE(CTEMP(ILEN))
         CALL BAREAD(LUGB,ISKIP,ILEN,LREAD,CTEMP)  ! READ IN SECTION
```

This seems to indicate that this subroutine is never used anywhere. If so, we should drop it...

@BoiVuong-NOAA and @Hang-Lei-NOAA do you know anything about this? Was there a past dependency on bacio? Is the subroutine GETGB2R() expected to work by anyone?

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #154 

Adding bacio back into NCEPLIBS-g2.

### CODE REVIEW

**Review by Hang-Lei-NOAA — APPROVED** [review]
You choose the safe way.

**Review by kgerheiser — CHANGES_REQUESTED** [review]
Need `find_dependency(bacio)` in the CMake package config

**Comment by edwardhartnett** [comment]
OK. Seems like jasper is also not being found by the CMake package config...

**Comment by kgerheiser** [comment]
Jasper is actually not necessary to add to `find_dependency`. Jasper doesn't use a CMake target (`jasper::jasper`) to define itself, using `${JASPER_LIBRARIES}` instead. When you link directly to libraries (`-l, -L`) like `JASPER_LIBRARIES` does it directly embeds itself in `INTERFACE_LINK_LIBRARIES` instead of needing to search for the target at build time like the package config does.

Point being that the Jasper library is hardcoded in the package config already because it doesn't use a target. Adding it here would just add it twice.

**Review by kgerheiser — APPROVED** [review]

**Pull request merged**
