### PR TITLE
update spack file

### LINKED ISSUE #782: spack file is out of date
The package file in the spack repo is ahead of what we have in our repo.

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #782 

I wish I had caught this before I merged the last PR, but I didn't...

This seems to wipe out a few lines about AEC in the repo version of the spack package file. @AlexanderRichert-NOAA what do we want to do, keep these?

### CODE REVIEW

**Comment by AlexanderRichert-NOAA** [comment]
Where are you seeing the AEC-related lines?

**Comment by edwardhartnett** [comment]
In this PR I just plonked the package file from the main spack repo on top of the repo's package file. As you can see in code review, this wipes out a few lines of package file code relating to AEC.

**Comment by AlexanderRichert-NOAA** [comment]
Ah okay I see it now. Yes we'll want to restore that.

**Comment by edwardhartnett** [comment]
@AlexanderRichert-NOAA I have tried but cannot figure out how this is breaking.

**Pull request closed without merging**
