### PR TITLE
cleanup of doxygen and adding hyperlinks

### PR DESCRIPTION
**Pull request by edwardhartnett**
Part of #132.

Only doxygen changes in this PR, no code changes...

### CODE REVIEW

**Review by Hang-Lei-NOAA — APPROVED** [review]

**Comment by Hang-Lei-NOAA** [comment]
gf_free also need to replace the deleted doxygen.

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA the deleted doxygen in gf_free (and in one other place) is just a repeat of the definitions of the gridmod fields. It's already in the gribmod docs.

**Comment by Hang-Lei-NOAA** [comment]
They are also parameters of gf_free. Missing will make the build of doxygen not pass.

**Comment by edwardhartnett** [comment]
I note that doxygen automatically makes a hyper-line when we use the name of a module in the documentation. Neat!

**Pull request merged**
