### PR TITLE
New test for getdim.f fix issue in test_getgb2

### PR DESCRIPTION
**Pull request by BrianCurtis-NOAA**
Add test for getdim.f

Current troubles: width and height do no come back correctly.

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
@edwardhartnett @Hang-Lei-NOAA do either of you know why the width and height do not come out of this call correctly?

Should be
```
width:    2
height:    2
``` 
but comes out 
```
width:    185405243
height:    989921280
```

**Comment by edwardhartnett** [comment]
Looks like a  mismatched type. Did you step through this code with debugger?

**Comment by BrianCurtis-NOAA** [comment]
> Looks like a mismatched type. Did you step through this code with debugger?

@edwardhartnett 
Yes, it seems the function wants only the GDS Char Arr.

Do you know what combinations of functions will spit out the proper csec3? I see a lot of g2_gbytec in other files that bring things to section 3 (from addgrid) but my work has been unsuccessful.

**Comment by edwardhartnett** [comment]
Maybe try this: https://github.com/NOAA-EMC/NCEPLIBS-g2c/blob/develop/tests/tst_getdim.c

but in Fortran...

**Comment by BrianCurtis-NOAA** [comment]
Screenshot from 2021-12-16 14-26-03

**Comment by Hang-Lei-NOAA** [comment]
What finally is the problem? @BrianCurtis-NOAA 
I was trying to examine your issue several days ago, but did not fully find the solution. 
Need to learn the issue.

**Comment by BrianCurtis-NOAA** [comment]
The issue was it wanted just the cgrib from section 3 (csec3) but I couldn't find the way to exactly get that from the grib file I was working with. There no function that I found (not saying there isn't one) that would spit out the section 3 information only. the unpack3 didn't spit out csec3 or lcsec3. Ed had hard coded a section 3 in the c version (g2c) that he told me to copy and so I did.

**Review by Hang-Lei-NOAA — APPROVED** [review]

**Pull request merged**
