### PR TITLE
Remove dependency on bacio

### PR DESCRIPTION
**Pull request by kgerheiser**

### CODE REVIEW

**Review by BoiVuong-NOAA — APPROVED** [review]
Looks good

**Comment by edwardhartnett** [comment]
Well it would be good to know why this was done, because there is still code from bacio in g2. ;-)

**Comment by BoiVuong-NOAA** [comment]
I think because user has never known this routine existing in G2 library.

**Comment by edwardhartnett** [comment]
Yet the routine was not removed, just the linking to bacio.

How do we know the function is not used?

**Comment by BoiVuong-NOAA** [comment]
I do not know the G2 has been introduced to public since 2008.

**Comment by edwardhartnett** [comment]
I don't really mind about the "public" using it. I care about any NOAA users using it...

**Comment by BoiVuong-NOAA** [comment]
I do not know.

**Pull request merged**
