### PR TITLE
Rename gbyte, gbytes, sbyte, sbytes

### PR DESCRIPTION
**Pull request by climbfuji**
This PR renames the four subroutines `gbyte`, `gbytes`, `sbyte`, `sbytes` by prepending `g2_` to each of them. This is required for linking against NCEPLIBS-g2 and NCEPLIBS-w3nco at the same time, because NCEPLIBS-w3nco contains subroutines with the same name and call signature. This can lead to unpredictable behavior or linker errors.

Tested to work on macOS and Redhat Linux thus far.

### CODE REVIEW

**Comment by climbfuji** [comment]
Ok, once this is merged I can do the final update of all the submodule pointers in the NCEPLIBS umbrella repo and finalize the changes. We should then be able to create beta02 tags for the NCEPLIBS-external and NCEPLIBS repos.

**Comment by BoiVuong-NOAA** [comment]
Hi Dom, We should rename gbytesc.f  to g2_gbytesc.f in G2 library.

**Comment by climbfuji** [comment]
> Hi Dom, We should rename gbytesc.f to g2_gbytesc.f in G2 library.

Done - still needs to be tested before merging.

**Comment by DusanJovic-NOAA** [comment]
Renaming this file and prefixing 4 subroutines with ``g2_`` is a good temporary solution. But there's still inconsistency between these routines and corresponding routines in ``w3nco`` library. For example ``SBYTE`` subroutine in this library is in fact ``SBYTEC`` in ``w3nco`` (subroutine that takes character array, hence ``C`` suffix), and ``SBYTE`` in ``w3nco`` is completely different implementation (using integer array). 

We should consider adding this ``C`` suffix to all 4 subroutines in ``g2_gbytesc.f``, Even the file name has ``c`` suffix.

**Comment by climbfuji** [comment]
> Renaming this file and prefixing 4 subroutines with `g2_` is a good temporary solution. But there's still inconsistency between these routines and corresponding routines in `w3nco` library. For example `SBYTE` subroutine in this library is in fact `SBYTEC` in `w3nco` (subroutine that takes character array, hence `C` suffix), and `SBYTE` in `w3nco` is completely different implementation (using integer array).
> 
> We should consider adding this `C` suffix to all 4 subroutines in `g2_gbytesc.f`. Even the file name has `c` suffix.

Ok, trying those changes now ...

**Comment by climbfuji** [comment]
> > Renaming this file and prefixing 4 subroutines with `g2_` is a good temporary solution. But there's still inconsistency between these routines and corresponding routines in `w3nco` library. For example `SBYTE` subroutine in this library is in fact `SBYTEC` in `w3nco` (subroutine that takes character array, hence `C` suffix), and `SBYTE` in `w3nco` is completely different implementation (using integer array).
> > We should consider adding this `C` suffix to all 4 subroutines in `g2_gbytesc.f`. Even the file name has `c` suffix.
> 
> Ok, trying those changes now ...

This works on macOS and gaea. Should be good to merge.

**Comment by BoiVuong-NOAA** [comment]
These routines look good.   We need to do more testing with some models.

**Comment by climbfuji** [comment]
Note that this PR is for the release/public-v1 branch. Not sure if your testing/build procedures are working with this branch.

**Comment by BoiVuong-NOAA** [comment]
I see. Are you going to merge it to release/public-v1 branch ?

**Comment by DusanJovic-NOAA** [comment]
I suggest we merge this PR and continue testing this branch with the UFS public release code. Develop (and master) branches should be tested more rigorously.

**Comment by climbfuji** [comment]
Ok, I will merge it. Thanks!

**Pull request merged**
